CREATE DATABASE BD_CONCESSIONARIA

USE BD_CONCESSIONARIA

DROP TABLE TB_MODELO

CREATE TABLE TB_MODELO
(

	  ID_MODELO	 TINYINT						IDENTITY 
	, DESCRICAO		 VARCHAR(30)					NOT NULL
	
	CONSTRAINT		 PK_ID_MODELO_TB_MODELO		    PRIMARY KEY	(ID_MODELO)

)


	INSERT INTO TB_MODELO
	(DESCRICAO)
	VALUES
	
	('RAM')
,	('Q3')
,	('CANAN')

	SELECT * FROM TB_MODELO
	
	

-- TABELA MODELO 




CREATE TABLE TB_ANO
(
		ID_ANO			TINYINT						IDENTITY
,		ANO				CHAR(4)						NOT NULL
	
	CONSTRAINT PK_ID_ANO_TB_ANO						PRIMARY KEY (ID_ANO)

)

	INSERT INTO TB_ANO
	(ANO)
	VALUES
	('2017')
,	('2018')
,	('2020')

	SELECT * FROM TB_ANO
	DROP TABLE TB_ANO

-- TABELA ANO



DROP TABLE TB_FABRICANTE
CREATE TABLE TB_FABRICANTE
(
	  ID_FABRICANTE			TINYINT				IDENTITY
	, NOME					VARCHAR	(50)		NOT NULL
	, CIDADE				VARCHAR	(50)		NOT NULL
	, ENDERECO				VARCHAR	(100)		
	, UF					CHAR	(2)
	, TELEFONE				VARCHAR	(13)		
	, CONTATO				VARCHAR	(50)		NOT NULL
	
	CONSTRAINT PK_ID_FABRICANTE_TB_FABRICANTE PRIMARY KEY (ID_FABRICANTE)

)

	INSERT INTO TB_FABRICANTE
	(NOME, CIDADE, ENDERECO,  UF, TELEFONE, CONTATO)
	VALUES
	('DODGE', 'SÃO PAULO', 'ALAMEDA DOS JUQUIS, 42', 'SP', '5511944675499',	'AUGUSTO COSTA' )
,	('AUDI', 'BELO HORIZONTE', 'RUA DOMINGO DE MORAES, 57', 'MG', '5531998752234', 'MARCIA KLEIN' )
,	('PORSCHE', 'SÃO PAULO', 'AVENIDA PAULISTA, 1034' , 'SP', '5511978941223', 'GABRIEL MAIORANI' )

	SELECT * FROM TB_FABRICANTE
	

-- TABELA FABRICANTE



                     --

DROP TABLE TB_MES
CREATE TABLE TB_MES
(
	ID_MES			TINYINT				IDENTITY(15,3)		NOT NULL
,	MES				VARCHAR(10)				

	CONSTRAINT		PK_ID_MES_TB_MES	PRIMARY KEY		(ID_MES)
)
	INSERT INTO TB_MES
	(MES)
	VALUES
	('FEVEREIRO')
,	('JULHO')
,	('NOVEMBRO')


	SELECT * FROM TB_MES
	

-- TABELA MES


-- IDENTITY_INSERT OFF (??) 
-- FOREIGN KEY

CREATE TABLE TB_VEICULO
(
	ID_VEICULO			TINYINT						IDENTITY
,	DESCRICAO_VEICULO	VARCHAR	(50)				NOT NULL	
,	VALOR				DECIMAL	(8,2)
,	ID_MODELO			TINYINT
,	ID_FABRICANTE		TINYINT
,	ID_ANOFABRICACAO	TINYINT
,	DATA_COMPRA			SMALLDATETIME				NOT NULL

	CONSTRAINT			PK_ID_VEICULO_TB_VEICULO				PRIMARY KEY		(ID_VEICULO)
	
	CONSTRAINT			FK_ID_MODELO_TB_MODELO					FOREIGN	KEY		(ID_MODELO)
	REFERENCES			TB_MODELO(ID_MODELO)

	,CONSTRAINT			FK_ID_FABRICANTE_TB_FABRICANTE			FOREIGN	KEY		(ID_FABRICANTE)
	REFERENCES			TB_FABRICANTE(ID_FABRICANTE)

	,CONSTRAINT			FK_ID_ANOFABRICACAO_TB_ANOFABRICACAO	FOREIGN	KEY		(ID_ANOFABRICACAO)
	REFERENCES			TB_ANO(ID_ANO)
)

	INSERT INTO TB_VEICULO
	(ID_VEICULO, DESCRICAO_VEICULO, VALOR, ID_MODELO, ID_FABRICANTE, ID_ANOFABRICACAO, DATA_COMPRA )
	VALUES
	('59356789', 'PRETO', '67.000,00', 'RAM', 'DODGE', '2017', '11-07-2017')
,	('67029481', 'AZUL', '53.500,00', 'Q3', 'AUDI', '2018', '23-08-2020')
,   ('12314535', 'ROXO', '87.750,50', 'CANAN', 'PORSCHE', '2020', '27-07-2020')

	
	
	SELECT * FROM TB_VEICULO
	DROP TABLE TB_VEICULO



CREATE TABLE TB_VENDAS_ANUAIS

(
	ID_VENDAS			TINYINT					IDENTITY
,	QTD					VARCHAR (50)			NOT NULL	
,	ID_VEICULO			TINYINT
,	ID_ANODAVENDA		TINYINT
,	ID_MESDAVENDA		TINYINT


	CONSTRAINT			PK_ID_VENDAS_TB_VENDAS_ANUAIS	PRIMARY KEY		(ID_VENDAS)

	,CONSTRAINT			FK_ID_VEICULO_TB_VEICULO		FOREIGN	KEY		(ID_VEICULO)
	REFERENCES			TB_VEICULO(ID_VEICULO)

	,CONSTRAINT			FK_ID_ANODAVENDA_TB_ANO			FOREIGN	KEY		(ID_ANODAVENDA)
	REFERENCES			TB_ANO(ID_ANO)

	,CONSTRAINT			FK_ID_MESDAVENDA_TB_MES			FOREIGN	KEY		(ID_MESDAVENDA)
	REFERENCES			TB_MES(ID_MES)
)


	INSERT INTO TB_VENDAS_ANUAIS
	(QTD, ID_VEICULO, ID_ANODAVENDA, ID_MESDAVENDA)
	VALUES
	('762','59356789','2017','02')
,	('1267','59356789','2017','02')
,	('500','59356789','2017','02')

	SELECT * FROM TB_VENDAS_ANUAIS
	DROP TABLE TB_VENDAS_ANUAIS